# Form implementation generated from reading ui file 'checktickets.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt6.QtWidgets import QMainWindow
import sys


class Ui_CheckTickets(object):
    def setupUi(self, CheckTickets):
        CheckTickets.setObjectName("CheckTickets")  # 设置窗口对象名称
        CheckTickets.resize(1170, 700)  # 设置窗口大小

        CheckTickets.setMinimumSize(QtCore.QSize(1170, 700))  # 主窗口最大值
        CheckTickets.setMaximumSize(QtCore.QSize(1170, 700))  # 主窗口最小值

        self.centralwidget = QtWidgets.QWidget(CheckTickets)  # 主窗口的widget控件
        self.centralwidget.setObjectName("centralwidget")  # 设置对象名称
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(5, 5, 1160, 120))
        self.label_img.setObjectName("label_img")

        img = QtGui.QPixmap(r'img.png')  # 打开顶部位图
        self.label_img.setPixmap(img)  # 设置调色板
        self.label_img.setScaledContents(True)  # 将图片缩放为控件尺寸

        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(5, 250, 1160, 450))
        self.tableView.setObjectName("tableView")
        self.widget_query = QtWidgets.QWidget(self.centralwidget)
        self.widget_query.setGeometry(QtCore.QRect(5, 125, 1165, 50))
        self.widget_query.setObjectName("widget_query")
        self.label_1 = QtWidgets.QLabel(self.widget_query)
        self.label_1.setGeometry(QtCore.QRect(5, 0, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_1.setFont(font)
        self.label_1.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.widget_query)
        self.label_2.setGeometry(QtCore.QRect(300, 0, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_query)
        self.label_3.setGeometry(QtCore.QRect(600, 0, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_query)
        self.pushButton.setGeometry(QtCore.QRect(950, 10, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.pushButton.setObjectName("pushButton")
        self.textEdit_1 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_1.setGeometry(QtCore.QRect(115, 10, 150, 30))
        self.textEdit_1.setObjectName("textEdit_1")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_2.setGeometry(QtCore.QRect(415, 10, 150, 30))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_3.setGeometry(QtCore.QRect(715, 10, 150, 30))
        self.textEdit_3.setObjectName("textEdit_3")
        self.widget_checkbox = QtWidgets.QWidget(self.centralwidget)
        self.widget_checkbox.setGeometry(QtCore.QRect(5, 180, 1165, 50))
        self.widget_checkbox.setObjectName("widget_checkbox")
        self.label_type = QtWidgets.QLabel(self.widget_checkbox)
        self.label_type.setGeometry(QtCore.QRect(50, 0, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_type.setFont(font)
        self.label_type.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight | QtCore.Qt.AlignmentFlag.AlignTrailing | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_type.setObjectName("label_type")
        self.checkBox_G = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_G.setGeometry(QtCore.QRect(200, 0, 120, 50))
        self.checkBox_G.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_G.setFont(font)
        self.checkBox_G.setStyleSheet("QCheckBox::indicator {width: 30px; height: 30px;}")
        self.checkBox_G.setObjectName("checkBox_G")
        self.checkBox_D = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_D.setGeometry(QtCore.QRect(350, 0, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_D.setFont(font)
        self.checkBox_D.setStyleSheet("QCheckBox::indicator {width: 30px; height: 30px;}")
        self.checkBox_D.setObjectName("checkBox_D")
        self.checkBox_Z = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_Z.setGeometry(QtCore.QRect(500, 0, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Z.setFont(font)
        self.checkBox_Z.setStyleSheet("QCheckBox::indicator {width: 30px; height: 30px;}")
        self.checkBox_Z.setObjectName("checkBox_Z")
        self.checkBox_T = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_T.setGeometry(QtCore.QRect(650, 0, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_T.setFont(font)
        self.checkBox_T.setStyleSheet("QCheckBox::indicator {width: 30px; height: 30px;}")
        self.checkBox_T.setObjectName("checkBox_T")
        self.checkBox_K = QtWidgets.QCheckBox(self.widget_checkbox)
        self.checkBox_K.setGeometry(QtCore.QRect(800, 0, 120, 50))
        self.checkBox_K.setSizeIncrement(QtCore.QSize(0, 0))
        self.checkBox_K.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_K.setFont(font)
        self.checkBox_K.setStyleSheet("QCheckBox::indicator {width: 30px; height: 30px;}")
        self.checkBox_K.setObjectName("checkBox_K")
        CheckTickets.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CheckTickets)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 22))
        self.menubar.setObjectName("menubar")
        CheckTickets.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CheckTickets)
        self.statusbar.setObjectName("statusbar")
        CheckTickets.setStatusBar(self.statusbar)

        self.retranslateUi(CheckTickets)
        QtCore.QMetaObject.connectSlotsByName(CheckTickets)

    def retranslateUi(self, CheckTickets):
        _translate = QtCore.QCoreApplication.translate
        CheckTickets.setWindowTitle(_translate("CheckTickets", "CheckTickets"))
        # self.label_img.setText(_translate("CheckTickets", "TextLabel"))
        self.label_1.setText(_translate("CheckTickets", "出发地："))
        self.label_2.setText(_translate("CheckTickets", "目的地："))
        self.label_3.setText(_translate("CheckTickets", "出发日："))
        self.pushButton.setText(_translate("CheckTickets", "查询"))
        self.label_type.setText(_translate("CheckTickets", "车次类型："))
        self.checkBox_G.setText(_translate("CheckTickets", "GC-高铁"))
        self.checkBox_D.setText(_translate("CheckTickets", "D-动车"))
        self.checkBox_Z.setText(_translate("CheckTickets", "Z-直达"))
        self.checkBox_T.setText(_translate("CheckTickets", "T-特快"))
        self.checkBox_K.setText(_translate("CheckTickets", "K-快速"))


def show_MainWindow():
    app = QtWidgets.QApplication(sys.argv)  # 实例化QAppication类，作为GUI主程序入口
    MainWindow = QtWidgets.QMainWindow()  # 创建MainWindow类
    ui = Ui_CheckTickets()  # 实例UI类
    ui.setupUi(MainWindow)  # 设置窗体UI
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec())  # 结束主循环过程


if __name__ == '__main__':
    show_MainWindow()
